# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'currentbabalance.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import os 
import sqlite3 

class Ui_current_balance(object):
    def setupUi(self, current_balance):
        current_balance.setObjectName("current_balance")
        current_balance.resize(1208, 825)
        current_balance.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        current_balance.setStyleSheet("color: rgb(163, 245, 245);\n"
"background-color: rgb(0, 0, 88);")
        self.label_3 = QtWidgets.QLabel(current_balance)
        self.label_3.setGeometry(QtCore.QRect(360, 380, 191, 51))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(current_balance)
        self.label_4.setGeometry(QtCore.QRect(360, 470, 191, 51))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(current_balance)
        self.label_6.setGeometry(QtCore.QRect(360, 570, 191, 51))
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(current_balance)
        self.label_7.setGeometry(QtCore.QRect(370, 300, 481, 41))
        self.label_7.setStyleSheet("border-color:rgb(255,255,255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 127);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset;")
        self.label_7.setObjectName("label_7")
        self.cus_name = QtWidgets.QLabel(current_balance)
        self.cus_name.setGeometry(QtCore.QRect(580, 380, 291, 51))
        self.cus_name.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(163, 245, 245);")
        self.cus_name.setText("")
        self.cus_name.setObjectName("cus_name")
        self.cus_balance = QtWidgets.QLabel(current_balance)
        self.cus_balance.setGeometry(QtCore.QRect(580, 570, 291, 51))
        self.cus_balance.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(163, 245, 245);")
        self.cus_balance.setText("")
        self.cus_balance.setObjectName("cus_balance")
        self.cus_type = QtWidgets.QLabel(current_balance)
        self.cus_type.setGeometry(QtCore.QRect(580, 470, 291, 51))
        self.cus_type.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(163, 245, 245);")
        self.cus_type.setText("")
        self.cus_type.setObjectName("cus_type")
        self.back_button = QtWidgets.QPushButton(current_balance)
        self.back_button.setGeometry(QtCore.QRect(170, 720, 171, 51))
        self.back_button.setStyleSheet("border-color:rgb(255,255,255);\n"
"\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.back_button.setObjectName("back_button")
        self.groupBox = QtWidgets.QGroupBox(current_balance)
        self.groupBox.setGeometry(QtCore.QRect(270, 30, 691, 231))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(160, 30, 372, 41))
        self.label_10.setStyleSheet("border-color:rgb(255,255,255);\n"
"font: 75 13pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 127);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset;")
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(110, 110, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.account_no = QtWidgets.QLineEdit(self.groupBox)
        self.account_no.setGeometry(QtCore.QRect(300, 110, 231, 41))
        self.account_no.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.account_no.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.account_no.setObjectName("account_no")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(530, 170, 121, 41))
        self.pushButton.setStyleSheet("border-color:rgb(255,255,255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset;")
        self.pushButton.setObjectName("search")
        self.clear_button = QtWidgets.QPushButton(current_balance)
        self.clear_button.setGeometry(QtCore.QRect(900, 710, 171, 51))
        self.clear_button.setStyleSheet("border-color:rgb(255,255,255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.clear_button.setObjectName("clear_button")
        self.retranslateUi(current_balance)
        QtCore.QMetaObject.connectSlotsByName(current_balance)
        self.pushButton.clicked.connect(self.search_func)
        self.clear_button.clicked.connect(self.clear_func)
    
    def clear_func(self,Dialog):
        self.acc_no.clear()
        self.cus_name.clear()
        self.cus_type.clear()
        self.cur_balance.clear()
        
    def search_func(self,Dialog):
        _translate = QtCore.QCoreApplication.translate
        global holder_name
        account_type="null"
        global avl_bal
        holder_name="null"
        avl_bal="0.0"
        conn = sqlite3.connect('aishu1.db')
        cur = conn.cursor()

        global ano
        ano=self.account_no.text()
        if ano!='':
            cur.execute('''SELECT account_number FROM customer''')
            result=cur.fetchall()
            b=[]
            for i in result:
                b.append(i[0])
        
        
            if int(ano) in b:
                cur.execute("select * from customer where account_number=? ",(ano,))
                result=cur.fetchall()
                for db in result:
                    holder_name=db[1]
                    account_type=db[2]
                    avl_bal=db[3]
                self.cus_name.setText(_translate("Dialog",holder_name ))
                self.cus_type.setText(_translate("Dialog",account_type ))
                self.cus_balance.setText(_translate("Dialog",str(avl_bal )))
                conn.commit 
            else :
                msg=QMessageBox()
                msg.setIcon(QMessageBox.Warning)
                msg.setText("account number doesnot exist")
                msg.setWindowTitle("error")
                msg.exec_()
                         
        else :
                msg=QMessageBox()
                msg.setIcon(QMessageBox.Warning)
                msg.setText("enter acc no")
                msg.setWindowTitle("error")
                msg.exec_()
                                    

    def retranslateUi(self, current_balance):
        _translate = QtCore.QCoreApplication.translate
        current_balance.setWindowTitle(_translate("current_balance", "Dialog"))
        self.label_3.setText(_translate("current_balance", "CUSTOMER NAME"))
        self.label_4.setText(_translate("current_balance", "ACCOUNT TYPE"))
        self.label_6.setText(_translate("current_balance", "CURRENT BALANCE"))
        self.label_7.setText(_translate("current_balance", "                     CURRENT BALANCE"))
        self.back_button.setText(_translate("current_balance", "BACK"))
        self.label_10.setText(_translate("current_balance", "             SEARCH ACCOUNT"))
        self.label.setText(_translate("current_balance", "ACCOUNT NUMBER"))
        self.pushButton.setText(_translate("current_balance", "SEARCH"))
        self.clear_button.setText(_translate("current_balance", "CLEAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    current_balance = QtWidgets.QDialog()
    ui = Ui_current_balance()
    ui.setupUi(current_balance)
    current_balance.show()
    sys.exit(app.exec_())
