# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import sqlite3 
conn= sqlite3.connect('BankNH.db')
cur = conn.cursor()

class Ui_login_page(object):
    def setupUi(self, login_page):
        login_page.setObjectName("login_page")
        login_page.resize(1415, 944)
        login_page.setStyleSheet("color: rgb(163, 245, 245);\n"
"background-color: rgb(0, 0, 88);\n"
"")
        self.groupBox = QtWidgets.QGroupBox(login_page)
        self.groupBox.setGeometry(QtCore.QRect(190, 100, 891, 661))
        self.groupBox.setStyleSheet("\n"
"background-color: rgb(0, 0, 100);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(360, 250, 161, 20))
        self.label_2.setMinimumSize(QtCore.QSize(161, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLineEdit(self.groupBox)
        self.name.setGeometry(QtCore.QRect(350, 280, 281, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.name.setFont(font)
        self.name.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radiu§s:10px;\n"
"border-style:outset")
        self.name.setText("")
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(360, 370, 171, 31))
        self.label_3.setStyleSheet("color: rgb(163, 245, 245);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(350, 410, 281, 41))
        self.password.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset\n"
"")
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.login_button = QtWidgets.QPushButton(self.groupBox)
        self.login_button.setGeometry(QtCore.QRect(320, 580, 261, 41))
        self.login_button.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset\n"
"")
        self.login_button.setObjectName("login_button")
        self.forgot_button = QtWidgets.QPushButton(self.groupBox)
        self.forgot_button.setGeometry(QtCore.QRect(490, 510, 141, 35))
        self.forgot_button.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset")
        self.forgot_button.setObjectName("forgot_button")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(350, 50, 201, 161))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("login_img1.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.signin_Button = QtWidgets.QPushButton(self.groupBox)
        self.signin_Button.setGeometry(QtCore.QRect(290, 510, 131, 35))
        self.signin_Button.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset")
        self.signin_Button.setObjectName("signin_Button")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(240, 250, 91, 81))
        self.label.setStyleSheet("background-image: url(:/Project/username_img.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("username_img.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(240, 370, 91, 91))
        self.label_5.setStyleSheet("background-image: url(:/Project/password_img.png);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("password_img.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(login_page)
        QtCore.QMetaObject.connectSlotsByName(login_page)
        self.login_button.clicked.connect(self.loginLogin)


    def generalmsg(self,title,message):
        msg=QMessageBox()     
        msg.setIcon(QMessageBox.Question)
        msg.setText(message)
        msg.setWindowTitle(title) 
        msg.exec_()
      
        
    def loginLogin(self):
        import sqlite3
        conn = sqlite3.connect('BankNH.db')
        cur = conn.cursor()
        uname = self.name.text()
        upassword = self.password.text()

        x=[]
        x.append(uname)
        cur.execute("SELECT password FROM newbank WHERE username = ? ", x)
        result = cur.fetchall()
        b=[]
        for i in result:
                b.append(i[0])
        print(b)        

        if upassword in str(b):
                self.generalmsg('successful','logined successfully')
                 #self.profile()
        else:
                print(upassword)
                self.generalmsg('warning ','incorect details')
              
    def retranslateUi(self, login_page):
        _translate = QtCore.QCoreApplication.translate
        login_page.setWindowTitle(_translate("login_page", "MainWindow"))
        self.label_2.setText(_translate("login_page", "USERNAME"))
        self.label_3.setText(_translate("login_page", "PASSWORD"))
        self.login_button.setText(_translate("login_page", "LOGIN"))
        self.forgot_button.setText(_translate("login_page", "Forgot Password ?"))
        self.signin_Button.setText(_translate("login_page", "SIGNIN"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_page = QtWidgets.QDialog()
    ui = Ui_login_page()
    ui.setupUi(login_page)
    login_page.show()
    sys.exit(app.exec_())
