# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'sign_in_page.ui'
# Created by: PyQt5 UI code generator 5.15.1
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import *
#import sys
import os

dbb = sqlite3.connect('BankNH.db')
c = dbb.cursor()
c.execute('''CREATE TABLE IF NOT EXISTS "newbank" (
	"userid"	INTEGER NOT NULL,
	"username"	TEXT NOT NULL,
	"phoneno"	INTEGER NOT NULL,
	"password"	INTEGER NOT NULL,
	PRIMARY KEY("userid" AUTOINCREMENT))''')

class Ui_signin_page(object):
    def setupUi(self, signin_page):
        signin_page.setObjectName("signin_page")
        signin_page.resize(1023, 786)
        signin_page.setStyleSheet("color: rgb(163, 245, 245);\n"
"background-color: rgb(0, 0, 88);\n"
"background-color: rgb(0, 0, 88);")
        self.centralwidget = QtWidgets.QWidget(signin_page)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(110, 40, 811, 671))
        self.groupBox.setStyleSheet("background-color: rgb(0, 0, 100);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(280, 90, 171, 31))
        self.label.setStyleSheet("background-color: rgb(0, 0, 88);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Sans Serif\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(280, 470, 271, 31))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 88);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Sans Serif\";\n"
"\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.username = QtWidgets.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(280, 130, 281, 41))
        self.username.setStyleSheet("font: 75 12pt \"MS Sans Serif\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset")
        self.username.setObjectName("username")

        self.confirm_password = QtWidgets.QLineEdit(self.groupBox)
        self.confirm_password.setGeometry(QtCore.QRect(280, 510, 281, 41))
        self.confirm_password.setStyleSheet("font: 75 12pt \"MS Sans Serif\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset")
        self.confirm_password.setObjectName("confirm_password")
        self.confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(280, 340, 221, 31))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 88);\n"
"border-color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"MS Sans Serif\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.new_password = QtWidgets.QLineEdit(self.groupBox)
        self.new_password.setGeometry(QtCore.QRect(280, 380, 281, 41))
        self.new_password.setStyleSheet("font: 75 12pt \"MS Sans Serif\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset")
        self.new_password.setObjectName("new_password")
        self.new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(280, 210, 171, 31))
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 88);\n"
"border-color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"MS Sans Serif\";")
        self.label_5.setObjectName("label_5")
        self.phoneno = QtWidgets.QLineEdit(self.groupBox)
        self.phoneno.setGeometry(QtCore.QRect(280, 250, 281, 41))
        self.phoneno.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset")
        self.phoneno.setObjectName("phoneno")
        self.signin_button = QtWidgets.QPushButton(self.groupBox)
        self.signin_button.setGeometry(QtCore.QRect(460, 590, 151, 41))
        self.signin_button.setStyleSheet("font: 14pt \"MS Sans Serif\";\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset")
        self.signin_button.setObjectName("signin_button")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(214, 100, 51, 71))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("username_img.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(194, 220, 71, 71))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Phone-Icon_img.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(204, 350, 61, 71))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("password_img.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(204, 480, 61, 71))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("password_img.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.signin_button_2 = QtWidgets.QPushButton(self.groupBox)
        self.signin_button_2.setGeometry(QtCore.QRect(220, 590, 151, 41))
        self.signin_button_2.setStyleSheet("font: 14pt \"MS Sans Serif\";\n"
"border-color: rgb(255, 255, 255);\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-style:outset")

        self.signin_button_2.setObjectName("signin_button_2")
        signin_page.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(signin_page)
        self.statusbar.setObjectName("statusbar")
        signin_page.setStatusBar(self.statusbar)

        self.retranslateUi(signin_page)
        QtCore.QMetaObject.connectSlotsByName(signin_page)
        self.username.setFocus(True)
        self.signin_button.clicked.connect(self.insertdb)
        self.signin_button_2.clicked.connect(self.login)

    def general_message(self, title, message):
        msg = QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(message)
        msg.setIcon(QMessageBox.Question)
        msg.exec_() 
    
    
    def insertdb(self):
        try:
                username = self.username.text()
                un="".join(username.split())
                if (un!="" and un.isalpha()==True):
                        password = self.new_password.text()
                        confirmPass = self.confirm_password.text()
                        if password and confirmPass!="":
                                if password != confirmPass:
                                        self.general_message('password Error', 'Password Not Match')
                                elif len(password) != len(confirmPass):
                                        self.general_message('password Error', 'password not Match')
                                else:
                                        phone = self.phoneno.text()
                                        if (phone.isdigit()==True):
                                        
                                                if len(self.phoneno.text()) != 10:
                                                        self.general_message('Invalid Number', 'please Check your Phone number')
                                                else:
                                                        c.execute("INSERT INTO newbank(username,password,phoneno)VALUES (?,?,?)", ( str(username), str(password), str(phone)))
                                                        dbb.commit()
                                                        dbb.close()
                                                        self.general_message('success','successfull creation')
                                                        self.login()
                                        else: 
                                            self.general_message('invalid','Please enter valid phone number ')                 
                        else:
                                self.general_message('invalid','Enter all details ')                                
                else:
                        self.general_message('invalid name','please enter Valid name')             
        except ValueError as e:
                self.general_message('invalid details','please enter valid details')

    def retranslateUi(self, signin_page):
        _translate = QtCore.QCoreApplication.translate
        signin_page.setWindowTitle(_translate("signin_page", "MainWindow"))
        self.label.setText(_translate("signin_page", "USERNAME"))
        self.label_3.setText(_translate("signin_page", "CONFIRM PASSWORD"))
        self.label_2.setText(_translate("signin_page", " NEW PASSWORD"))
        self.label_5.setText(_translate("signin_page", "PHONE NUMBER"))
        self.signin_button.setText(_translate("signin_page", "SIGN IN"))
        self.signin_button_2.setText(_translate("signin_page", "BACK"))

    def login(self): 
        from login1 import Ui_login_page
        self.login_page = QtWidgets.QWidget()
        self.ui = Ui_login_page()
        self.ui.setupUi(self.login_page)
        signin_page.close()
        self.login_page.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signin_page = QtWidgets.QMainWindow()
    ui = Ui_signin_page()
    ui.setupUi(signin_page)
    signin_page.show()
    sys.exit(app.exec_())
